// common/constants/achievements.ts

export type Achievement = {
    id: number;
    title: string;
    issuer: string;
    date: string;
    credential: string;
    link?: string;
    type: string;
    category: string;
    image: string;
    tags: string[];
};

export const achievements: Achievement[] = [
    {
        id: 15,
        title: "Belajar Dasar AI",
        issuer: "Dicoding",
        date: "Juli 2026",
        credential: "1RXYW5V73ZVM",
        link: "https://www.dicoding.com/certificates/1RXYW5V73ZVM",
        type: "Certificate",
        category: "Artificial Intelligence",
        image: "/images/achievments/sertifikat-dicoding-ai.png",
        tags: ["AI", "Machine Learning", "Dicoding"],
    },
    {
        id: 1,
        title: "Software Engineering Level Test XI",
        issuer: "SMK Taruna Bhakti",
        date: "Juni 2026",
        credential: "",
        type: "Certificate",
        category: "Software Engineering",
        image: "/images/achievments/sertifikat-uji-level-xi.jpeg",
        tags: ["RPL", "FullStack"],
    },
    {
        id: 2,
        title: "Online Class Professional Model Makeup & Offline Portfolio Batch 5",
        issuer: "Million Model Agency",
        date: "Januari 2026",
        credential: "",
        type: "Certificate",
        category: "Non-Technical",
        image: "/images/achievments/sertifikat-million-model.jpeg",
        tags: ["Modeling", "Makeup"],
    },
    {
        id: 7,
        title: "Juara 1 Lomba Paduan Suara — Hari Sumpah Pemuda & Bulan Bahasa",
        issuer: "SMK Taruna Bhakti",
        date: "Oktober 2025",
        credential: "",
        type: "Certificate",
        category: "Competition",
        image: "/images/achievments/sertifikat-paduan-suara.jpeg",
        tags: ["Competition", "Choir"],
    },
    {
        id: 8,
        title: "Bachelor of Science Nursing — CNA Simulator",
        issuer: "Roblox University",
        date: "Juli 2025",
        credential: "",
        type: "Certificate",
        category: "Gaming",
        image: "/images/achievments/sertifikat-roblox-nursing.jpeg",
        tags: ["Roblox", "Gaming"],
    },
    {
        id: 3,
        title: "Bendahara OSIS Periode 2024/2025",
        issuer: "SMK Taruna Bhakti",
        date: "2024-2025",
        credential: "",
        type: "Certificate",
        category: "Organization",
        image: "/images/achievments/sertifikat-osis.jpeg",
        tags: ["OSIS", "Leadership"],
    },
    {
        id: 4,
        title: "Software Engineering Level Test X",
        issuer: "SMK Taruna Bhakti",
        date: "Juni 2025",
        credential: "",
        type: "Certificate",
        category: "Software Engineering",
        image: "/images/achievments/sertifikat-uji-level-x.jpeg",
        tags: ["RPL", "FullStack"],
    },
    {
        id: 5,
        title: "Kunjungan Industri PT INTI & ITB",
        issuer: "SMK Taruna Bhakti",
        date: "Januari 2025",
        credential: "",
        type: "Certificate",
        category: "Industry Visit",
        image: "/images/achievments/sertifikat-kunjungan-industri.jpeg",
        tags: ["Industry", "Networking"],
    },
    {
        id: 6,
        title: "Belajar Dasar Pemrograman Web",
        issuer: "Dicoding",
        date: "November 2024",
        credential: "2VX3R7DL3ZYQ",
        link: "https://www.dicoding.com/certificates/2VX3R7DL3ZYQ",
        type: "Certificate",
        category: "Web Development",
        image: "/images/achievments/sertifikat-dicoding-1.png",
        tags: ["Web", "Programming"],
    },
    {
        id: 14,
        title: "Elementary School Graduation Certificate",
        issuer: "SD Inklusi Al-Irsyad Al-Islamiyyah Depok",
        date: "Juni 2021",
        credential: "SK-02/D-SD/K.13/0726325/MI/2021",
        type: "Certificate",
        category: "Education",
        image: "/images/achievments/sertifikat-kelulusan-sd.jpeg",
        tags: ["Elementary School", "Graduation"],
    },
    {
        id: 13,
        title: "Ramadan Islamic Camp",
        issuer: "SD Inklusi Al-Irsyad Al-Islamiyyah Depok",
        date: "Juni 2016",
        credential: "",
        type: "Certificate",
        category: "Religious Education",
        image: "/images/achievments/sertifikat-pesantren-ramadhan.jpeg",
        tags: ["Ramadan"],
    },
    {
        id: 9,
        title: "Drum Band Training",
        issuer: "Persatuan Drum Band Indonesia & RA Al-Muhajirin II",
        date: "2015",
        credential: "",
        type: "Certificate",
        category: "Extracurricular",
        image: "/images/achievments/sertifikat-drumband-2015.jpeg",
        tags: ["Drum Band", "Music"],
    },
    {
        id: 11,
        title: "Painting Extracurricular Program",
        issuer: "Sanggar Lukis Anak IDOLA & RA Al-Muhajirin II",
        date: "Juni 2015",
        credential: "",
        type: "Certificate",
        category: "Extracurricular",
        image: "/images/achievments/sertifikat-melukis.jpeg",
        tags: ["Painting", "Art"],
    },
    {
        id: 12,
        title: "English Extracurricular Program",
        issuer: "RA Al-Muhajirin II",
        date: "Juni 2015",
        credential: "",
        type: "Certificate",
        category: "Extracurricular",
        image: "/images/achievments/sertifikat-bahasa-inggris.jpeg",
        tags: ["English", "Language"],
    },
    {
        id: 10,
        title: "Manasik Haji Demonstration Participant",
        issuer: "PD. IGRA Kota Depok",
        date: "November 2014",
        credential: "",
        type: "Certificate",
        category: "Extracurricular",
        image: "/images/achievments/piagam-manasik-haji-2014.jpeg",
        tags: ["Manasik Haji"],
    },
];